version: '2'
services:
  web:
    build:
      context: .
    tty: true
    stdin_open: true
    ports:
      - "80:3000"
    links:
      - postgres
    environment:
      POCKET_DATABASE_HOST: postgres
      POCKET_DATABASE_PASSWORD: password
    volumes:
      - ./:/pocket
  postgres:
    image: postgres:10.4
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata:
    driver: local