default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: pocket_development

test:
  <<: *default
  database: pocket_test

staging:
  <<: *default
  database: pocket_staging

production:
  <<: *default
  database: pocket_production
  username: pocket
  password: <%= ENV['POCKET_DATABASE_PASSWORD'] %>
