default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: <%= ENV['POCKET_DATABASE_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: pocket_development
  host: <%= ENV['POCKET_DATABASE_HOST'] %>

test:
  <<: *default
  database: pocket_test
  host: <%= ENV['POCKET_DATABASE_HOST'] %>

staging:
  <<: *default
  database: pocket_staging

production:
  <<: *default
  database: pocket_production
  username: postgres
